### PR TITLE
[#307] Improve KNN with n_neighbours parameter

### PR DESCRIPTION
**Pull request by Imipenem**
**PR Checklist**

-   [x] This comment contains a description of changes (with reason)
-   [x] Referenced issue is linked
-   [x] If you've fixed a bug or added code that should be tested, add tests!
-   [x] Documentation in `docs` is updated

**Description of changes**

- added n_neighbours parameter to knn impute

- encoding now only gets applied to non numerical columns

- added tests for knn impute with n_neighbours parameter

### CODE REVIEW

**Comment by Imipenem** [comment]
@Zethson Note: The current implementation just cuts off the float part of the encoded values of non numerical columns and use this for the int value. There is a `numpy` function that does a more natural behaviour (actual rounding: 2.4 -> 2, 2.6 -> 3). But somehow, this didn't work on `float` input with some strange errors (at least for me).

**Comment by Zethson** [comment]
1. What happens in the case of categorical values?
2. What's the error with the floats? Totally not happy with the int casting. For some blood measurements or whatever this is kinda unacceptable, no?

**Comment by Imipenem** [comment]
> 1. What happens in the case of categorical values?
> 
>     2. What's the error with the floats? Totally not happy with the int casting. For some blood measurements or whatever this is kinda unacceptable, no?

Its fixed, but it kind of shows the downside when using numpy array with dtype object. Many of the `ufuncs` of numpy are not defined on object dtype arrays (like `isnan` or `rint` or `round`).

**Comment by Zethson** [comment]
So there's still some casting for ints left. Why is that? Just trying to understand.

**Comment by Zethson** [comment]
Yup, I understood it correctly. Thanks. Approved

**Pull request merged**
