### PR TITLE
Consistent US spelling in docs and fix typos

### LINKED ISSUE #740: UK or US spelling or both for functions
### Description of feature

Nice input from elsewhere:

Should be using either UK or US spelling for the functions included in ehrapy (e.g. ep.pp.neighbors(adata) vs. ep.pp.knn_impute(adata, n_neighbours=20)) or enabling both.

- [ ] Update [ehrapy-reproducibility](https://github.com/theislab/ehrapy-reproducibility)
- [ ] Update [ehrapy-tutorials](https://github.com/theislab/ehrapy-tutorials)

### PR DESCRIPTION
**Pull request by eroell**
**PR Checklist**

-   [x] This comment contains a description of changes (with reason)
-   [x] Referenced issue is linked: Fixes #740 
-   [ ] If you've fixed a bug or added code that should be tested, add tests! N/A
-   [x] Documentation in `docs` is updated
-   [ ] readthedocs rendering of affected parts visually inspected

**Description of changes**
- Use consistently the American "neighbors" instead of "neighbours"
- Changes to documentation focusing on typos.

**Technical details**
- This is an API level change

**Additional context**
- Maintain backwards compatibility, or break `ep.pp.knn_impute(..., n_neighbours)`? -> keep backwards compatibility

### CODE REVIEW

**Comment by Zethson** [comment]
I love PRs like these. I'd advocate to keep backwards compatibility. It should be easy with kwargs. It's one of the few parameters that people probably use. This should also fix the tutorial CI :)

**Comment by eroell** [comment]
Something completely different:

https://github.com/theislab/ehrapy/blob/38bd3495d1bd091fd7a731510fdbba5584674bca/ehrapy/tools/feature_ranking/_rank_features_groups.py#L330

This line should be deleted in my opinion. Right?

**Comment by Zethson** [comment]
> Something completely different:
> 
> https://github.com/theislab/ehrapy/blob/38bd3495d1bd091fd7a731510fdbba5584674bca/ehrapy/tools/feature_ranking/_rank_features_groups.py#L330
> 
> This line should be deleted in my opinion. Right?

Yeah I guess so

**Comment by eroell** [comment]
> This should also fix the tutorial CI :)

It wont though if an old ehrapy version is used, and the tutorial uses `n_neighbors`...
But we're ready to help if someone runs into this :)

**Pull request merged**
